stages:
  - build
  - package

variables:
  YARN_CACHE_FOLDER: '${CI_PROJECT_DIR}/.cache/yarn'

.cache:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/yarn

install:
  stage: build
  extends: .cache
  image: node:14-slim
  script:
    - yarn --frozen-lockfile --silent
  only:
    changes:
      - yarn.lock

.docker:
  image: docker:19-dind
  services:
    - docker:19-dind
  tags:
    - cluster
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.app:
  script:
    - docker pull $DOCKER_RELEASE_IMAGE || true
    - docker build --cache-from $DOCKER_RELEASE_IMAGE --tag
      $DOCKER_CURRENT_IMAGE --tag $DOCKER_RELEASE_IMAGE .
    - docker push $DOCKER_CURRENT_IMAGE
    - docker push $DOCKER_RELEASE_IMAGE

package:app:dev:
  stage: package
  extends:
    - .docker
    - .app
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/sola:latest
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/sola:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

package:app:release:
  stage: package
  extends:
    - .docker
    - .app
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/sola:release
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/sola:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG != null'
