version: '2'

services:
  app:
    image: registry.gitlab.com/acdh-oeaw/sola/sola:latest
    volumes:
      - image_cache:/app/.next/cache/images
    labels:
      - traefik.backend=sola
      - traefik.frontend.rule=Host:sola.sisyphos.arz.oeaw.ac.at
      - traefik.docker.network=web
      - traefik.port=3000
      - ID=17540
      - BackendConnection=none
    networks:
      - web

volumes:
  image_cache:

networks:
  web:
    external:
      name: web
